POST http://localhost:8080/order
Content-Type: application/json

{
  "id": 3,
  "user": "홍길동2",
  "vendor": "서초점2",
  "items": [
    {
      "id": 1,
      "name": "코카콜라",
      "quantity": 1
    },
    {
      "id": 2,
      "name": "펩시",
      "quantity": 2
    }
  ]
}